/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                  '#0a0e1a',
        'surface-dim':              '#0a0e1a',
        'surface-bright':           '#1f2b49',
        'surface-container-lowest': '#050810',
        'surface-container-low':    '#0e1424',
        'surface-container':        '#131b2e',
        'surface-container-high':   '#1a2340',
        'surface-container-highest':'#1f2a4a',
        'surface-variant':          '#1f2a4a',
        'background':               '#0a0e1a',
        'on-background':            '#e2e8ff',
        'on-surface':               '#e2e8ff',
        'on-surface-variant':       '#8891ab',
        'inverse-surface':          '#faf8ff',
        'inverse-on-surface':       '#4d556b',
        'outline':                  '#6d758c',
        'outline-variant':          '#2a3350',
        'surface-tint':             '#3bbffa',
        'primary':                  '#3bbffa',
        'primary-dim':              '#05a9e3',
        'primary-fixed':            '#2db7f2',
        'primary-fixed-dim':        '#05a9e3',
        'primary-container':        '#22b1ec',
        'on-primary':               '#00374d',
        'on-primary-fixed':         '#00121d',
        'on-primary-fixed-variant': '#003a50',
        'on-primary-container':     '#002b3d',
        'inverse-primary':          '#00668b',
        'secondary':                '#69f6b8',
        'secondary-dim':            '#58e7ab',
        'secondary-fixed':          '#69f6b8',
        'secondary-fixed-dim':      '#58e7ab',
        'secondary-container':      '#006c49',
        'on-secondary':             '#005a3c',
        'on-secondary-fixed':       '#00452d',
        'on-secondary-fixed-variant':'#006544',
        'on-secondary-container':   '#e1ffec',
        'tertiary':                 '#919bff',
        'tertiary-dim':             '#8a95ff',
        'tertiary-fixed':           '#a2aaff',
        'tertiary-fixed-dim':       '#919bff',
        'tertiary-container':       '#818cf8',
        'on-tertiary':              '#000b83',
        'on-tertiary-fixed':        '#00055d',
        'on-tertiary-fixed-variant':'#1f2a95',
        'on-tertiary-container':    '#00055a',
        'error':                    '#ff716c',
        'error-dim':                '#d7383b',
        'error-container':          '#9f0519',
        'on-error':                 '#490006',
        'on-error-container':       '#ffa8a3',
        'warn':                     '#ffd93d',
        'warn-container':           'rgba(255, 217, 61, 0.08)',
      },
      fontFamily: {
        headline: ['"Chakra Petch"', 'sans-serif'],
        body:     ['"Hanken Grotesk"', 'sans-serif'],
        label:    ['"JetBrains Mono"', 'monospace'],
        mono:     ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm:      '6px',
        md:      '10px',
        lg:      '14px',
        xl:      '18px',
        '2xl':   '24px',
        '3xl':   '32px',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
