/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                  '#060e20',
        'surface-dim':              '#060e20',
        'surface-bright':           '#1f2b49',
        'surface-container-lowest': '#000000',
        'surface-container-low':    '#091328',
        'surface-container':        '#0f1930',
        'surface-container-high':   '#141f38',
        'surface-container-highest':'#192540',
        'surface-variant':          '#192540',
        'background':               '#060e20',
        'on-background':            '#dee5ff',
        'on-surface':               '#dee5ff',
        'on-surface-variant':       '#a3aac4',
        'inverse-surface':          '#faf8ff',
        'inverse-on-surface':       '#4d556b',
        'outline':                  '#6d758c',
        'outline-variant':          '#40485d',
        'surface-tint':             '#3bbffa',
        'primary':                  '#3bbffa',
        'primary-dim':              '#05a9e3',
        'primary-fixed':            '#2db7f2',
        'primary-fixed-dim':        '#05a9e3',
        'primary-container':        '#22b1ec',
        'on-primary':               '#00374d',
        'on-primary-fixed':         '#00121d',
        'on-primary-fixed-variant': '#003a50',
        'on-primary-container':     '#002b3d',
        'inverse-primary':          '#00668b',
        'secondary':                '#69f6b8',
        'secondary-dim':            '#58e7ab',
        'secondary-fixed':          '#69f6b8',
        'secondary-fixed-dim':      '#58e7ab',
        'secondary-container':      '#006c49',
        'on-secondary':             '#005a3c',
        'on-secondary-fixed':       '#00452d',
        'on-secondary-fixed-variant':'#006544',
        'on-secondary-container':   '#e1ffec',
        'tertiary':                 '#919bff',
        'tertiary-dim':             '#8a95ff',
        'tertiary-fixed':           '#a2aaff',
        'tertiary-fixed-dim':       '#919bff',
        'tertiary-container':       '#818cf8',
        'on-tertiary':              '#000b83',
        'on-tertiary-fixed':        '#00055d',
        'on-tertiary-fixed-variant':'#1f2a95',
        'on-tertiary-container':    '#00055a',
        'error':                    '#ff716c',
        'error-dim':                '#d7383b',
        'error-container':          '#9f0519',
        'on-error':                 '#490006',
        'on-error-container':       '#ffa8a3',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body:     ['"Inter"', 'sans-serif'],
        label:    ['"Space Grotesk"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
